#!/usr/bin/env bash
#
# Deploy docs_curated/ to GitHub Pages, with all large binary assets
# served from GitHub Release permanent URLs (no S3 dependency at runtime).
#
# Pre-requisites (one-time):
#
#   1) gh CLI authenticated:
#        gh auth login
#      or in CI:  export GH_TOKEN=ghp_xxx
#
#   2) Create the GitHub repo + release once:
#        gh repo create haoz19/world-tracing-page --public \
#            --description "Multilayer Depth - World Tracing - project page"
#        gh release create v1 -R haoz19/world-tracing-page \
#            --title "Project page assets v1" \
#            --notes "Permanent RRD / wtpc / glb / mp4 assets used by the demo page."
#
#   3) Upload all 151 release assets (1.85 GB) ONCE:
#        python _upload_release_full.py
#
# This deploy script (idempotent, run after every page-content change):
#
#   * Regenerates _s3_override.js so every URL resolves to a GitHub
#     Release asset (no presigned URLs, never expires).
#   * Rebuilds standalone.html with that override injected.
#   * Pushes docs_curated/ (HTML / JS / CSS / 1 MB thumbnails) to the
#     ``gh-pages`` branch via `git worktree`.
#
# Usage::
#
#     bash _deploy_gh_pages.sh
#     bash _deploy_gh_pages.sh --skip-rebuild   # just re-push existing files
#     bash _deploy_gh_pages.sh --check-release  # report missing release assets
#

set -euo pipefail

cd /mnt/filestore/users/hao/wlt/src/wlt/experimental/users/hao/multilayer_depth_release_inference

GH_USER="${GH_USER:-haoz19}"
GH_REPO="${GH_REPO:-world-tracing-page}"
GH_TAG="${GH_TAG:-v1}"
REPO_FULL="${GH_USER}/${GH_REPO}"
PAGES_BRANCH="${PAGES_BRANCH:-gh-pages}"

MODE="full"
for arg in "$@"; do
    case "$arg" in
        --skip-rebuild) MODE="skip-rebuild" ;;
        --check-release) MODE="check-release" ;;
        --skip-push) MODE="skip-push" ;;
    esac
done

echo "Target: github.com/${REPO_FULL}  branch=${PAGES_BRANCH}  release-tag=${GH_TAG}"

###############################################################################
# Step 0  Validate gh login.
###############################################################################

if ! gh auth status >/dev/null 2>&1; then
    echo "ERROR: gh CLI not authenticated.  Run 'gh auth login' first." >&2
    exit 1
fi

###############################################################################
# Step 1  (Optional) audit: report any release assets that are missing.
###############################################################################

if [[ "$MODE" == "check-release" ]]; then
    echo "=== checking release ${GH_TAG} for missing assets ==="
    python3 _upload_release_full.py \
        --gh-user "$GH_USER" --gh-repo "$GH_REPO" --gh-tag "$GH_TAG" --dry-run \
        | head -10
    echo "(run 'python _upload_release_full.py' to upload missing files)"
    exit 0
fi

###############################################################################
# Step 2  Rebuild the page with GitHub Release URLs baked in.
###############################################################################

if [[ "$MODE" != "skip-rebuild" ]]; then
    echo "=== regenerating docs_curated/* with release URLs ==="
    python3 _build_curated_page.py \
        --out-dir docs_curated \
        --gh-user "$GH_USER" --gh-repo "$GH_REPO" --gh-tag "$GH_TAG"

    echo "=== building _s3_override.js with GH Release URLs ==="
    python3 _build_release_override.py \
        --gh-user "$GH_USER" --gh-repo "$GH_REPO" --gh-tag "$GH_TAG"

    echo "=== injecting override into standalone.html ==="
    python3 <<'PY'
from pathlib import Path

sa_path = Path("docs_curated/standalone.html")
ov_path = Path("docs_curated/_s3_override.js")
sa = sa_path.read_text()
override = ov_path.read_text()

OVERRIDE_BEGIN = "// __WT_S3_OVERRIDE_BEGIN__\n"
OVERRIDE_END   = "// __WT_S3_OVERRIDE_END__\n"
while OVERRIDE_BEGIN in sa:
    s = sa.find(OVERRIDE_BEGIN)
    e = sa.find(OVERRIDE_END, s)
    if e == -1:
        print("WARN: dangling OVERRIDE_BEGIN; leaving file as-is")
        break
    sa = sa[:s] + sa[e + len(OVERRIDE_END):]

# Drop any legacy S3-presigned override blocks generated by the old
# _upload_curated_page_s3.sh path (everything from
# '\n// runtime override' up to the next </script>).
legacy = sa.find("\n// runtime override")
if legacy != -1:
    end_legacy = sa.find("</script>", legacy)
    if end_legacy != -1:
        sa = sa[:legacy] + sa[end_legacy:]

def _end_of_window_assign(sa: str, name: str) -> int:
    needle = f"window.{name} = "
    i = sa.find(needle)
    if i == -1:
        return -1
    p = i + len(needle)
    while p < len(sa) and sa[p] in " \t\n":
        p += 1
    if p >= len(sa) or sa[p] not in "[{":
        return -1
    opener = sa[p]; closer = "]" if opener == "[" else "}"
    depth = 1; p += 1
    while p < len(sa) and depth > 0:
        ch = sa[p]
        if ch == opener: depth += 1
        elif ch == closer: depth -= 1
        elif ch == '"':
            p += 1
            while p < len(sa) and sa[p] != '"':
                if sa[p] == "\\" and p + 1 < len(sa):
                    p += 1
                p += 1
        p += 1
    if p < len(sa) and sa[p] == ";":
        p += 1
    return p

positions = []
for nm in ("SAMPLES", "DEMO_VIDEOS", "SECTION_VIDEOS"):
    pos = _end_of_window_assign(sa, nm)
    if pos != -1:
        positions.append((nm, pos))

if not positions:
    print("WARN: no window.SAMPLES/DEMO_VIDEOS/SECTION_VIDEOS found; override NOT injected")
else:
    j = max(p for _, p in positions)
    delimited = OVERRIDE_BEGIN + override + OVERRIDE_END
    sa = sa[:j] + delimited + sa[j:]
    sa_path.write_text(sa)
    print(f"injected override ({len(delimited)} bytes) at pos {j}")
PY

    # index.html also loads the (separate) _s3_override.js file via a
    # <script> tag, so nothing extra is needed; it picks up the new file
    # at next page load.
fi

###############################################################################
# Step 3  Push docs_curated/ contents to gh-pages branch via git worktree.
###############################################################################

if [[ "$MODE" == "skip-push" ]]; then
    echo "skipping push (--skip-push); files ready under docs_curated/"
    exit 0
fi

echo "=== preparing gh-pages branch ==="

WORKDIR="$(mktemp -d /tmp/world-tracing-page-deploy.XXXXXX)"
echo "  workdir: $WORKDIR"

# Clone the (currently empty) repo. If the repo just got created and is
# empty, the clone will produce an empty working tree on the default
# branch -- that's fine; we'll create gh-pages explicitly.
git clone "https://github.com/${REPO_FULL}.git" "$WORKDIR" || {
    echo "ERROR: could not clone github.com/${REPO_FULL}."
    echo "       Did you create the repo?"
    echo "         gh repo create $REPO_FULL --public --description '...'"
    exit 1
}
cd "$WORKDIR"

# Configure git identity from the gh user if not already set in this
# fresh clone. (We do NOT touch the user's global git config.)
git config user.email "${GIT_AUTHOR_EMAIL:-haoz19@users.noreply.github.com}"
git config user.name  "${GIT_AUTHOR_NAME:-haoz19}"

# Get onto a clean gh-pages branch (create if missing).
if git ls-remote --exit-code --heads origin "$PAGES_BRANCH" >/dev/null 2>&1; then
    echo "  fetching existing $PAGES_BRANCH"
    git fetch origin "$PAGES_BRANCH"
    git checkout -B "$PAGES_BRANCH" "origin/$PAGES_BRANCH"
    # Wipe everything (keep .git) so removed files actually get removed.
    git rm -rf . >/dev/null 2>&1 || true
else
    echo "  creating new $PAGES_BRANCH (orphan)"
    git checkout --orphan "$PAGES_BRANCH"
    git rm -rf . >/dev/null 2>&1 || true
fi

# Copy the page contents. Exclude large local-only artefacts.
echo "=== copying docs_curated/ -> worktree ==="
rsync -a --delete \
    --exclude='_release_manifest.json' \
    --exclude='_s3_urls.json' \
    --exclude='_section_videos.json' \
    --exclude='_highlight_videos.json' \
    --exclude='_demo_videos.json' \
    /mnt/filestore/users/hao/wlt/src/wlt/experimental/users/hao/multilayer_depth_release_inference/docs_curated/ ./

# A .nojekyll file disables Jekyll on GH Pages so files starting with `_`
# (such as `_s3_override.js`) are served.
touch .nojekyll

du -sh . | sed 's/^/  page worktree size: /'

git add -A
if git diff --cached --quiet; then
    echo "  no changes to commit; nothing to push"
else
    git commit -m "deploy: project page at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "=== pushing $PAGES_BRANCH ==="
    git push origin "$PAGES_BRANCH"
fi

echo
echo "================================================================"
echo "DONE.  Page will be live at:"
echo "    https://${GH_USER}.github.io/${GH_REPO}/"
echo "  (you may need to enable Pages once, see step below)"
echo "================================================================"
echo
echo "FIRST-TIME PAGES ENABLE:"
echo "  open https://github.com/${REPO_FULL}/settings/pages"
echo "  set 'Build and deployment' Source = 'Deploy from a branch'"
echo "  set Branch = '${PAGES_BRANCH}' / '/(root)' / Save"
echo "  wait 1-2 min, refresh https://${GH_USER}.github.io/${GH_REPO}/"

rm -rf "$WORKDIR"
